### PR TITLE
Deployed Resource Cleanup

### PR DESCRIPTION
**Pull request by mbrat2005**
Adds the following tag/metadata/description to resources deployed by ALZ-Monitor to ensure they can effectively be cleaned up.

	- Metric and Query Rule Alerts:
		○ Tag: _deployed_by_alz_monitor: true
	- Policy definitions:
		○ Metadata: source: 'https://github.com/Azure/ALZ-Monitor/'
	- Policy set defintions: 
		○ Metadata: "source": "https://github.com/Azure/ALZ-Monitor/"
	- Policy assignments:
		○ Metadata: _deployed_by_alz_monitor: true
        - Policy assignment role assignments: 
                ○  Description contains '_deployed_by_alz_monitor'

Adds the script src\scripts\Start-ALZMonitorCleanup.ps1 to execute the cleanup. The script uses Resource Graph to gather resources across all accessible Management Groups for removal. Includes -WhatIf and -ReportOnly functionality for dry runs and evaluation.

### CODE REVIEW

**Comment by mbrat2005** [comment]
@jfaurskov My fork of the repo seems to have become disassociated with the main project--perhaps because I added Mahesh and Sacha with access? I think I need to close this PR and open a new one from a new fork. I did make some changes following feedback...

**Comment by paulgrimley** [comment]
@mbrat2005 as we've just gone public with the repo one of the side effects is it breaks your fork so you will need to re fork i'm afraid

**Comment by mbrat2005** [comment]
Created a new PR from a new fork (required after alz-monitor went public). See: https://github.com/Azure/alz-monitor/pull/139

**Comment by mbrat2005** [comment]
Thanks Paul, I recreated the PR from a new fork and closed the old one.
________________________________

**Pull request closed without merging**
