### PR TITLE
Alleviating Parameter confusion

### PR DESCRIPTION
**Pull request by pkorolo**
This is for User Story 28605

### CODE REVIEW

**Review by arjenhuitema — CHANGES_REQUESTED** [review]
Thanks @pkorolo, the changes to the document are great and it clarifies very well the use of the current parameters.

To further clarify, I suggest changing the parameter names. When assigning the initiatives, the parameter name is nearly identical to the cli parameter.  

Deployment variable:
`**managementGroupId**="The pseudo root management group id"`

Assigning initiative:
`az deployment mg create --template-file ./infra-as-code/bicep/assign_initiatives_identity.bicep --location $location **--management-group-id** $identityManagementGroup --parameters ./infra-as-code/bicep/parameters-complete-identity.json`

Parameter file:
```
        "**parPolicyManagementGroupId**": {

            "value": "alz"
```


I think we should change the naming of our parameters that reference the "top-level/ pseudo root" into something more descriptive like psuedoRootManagementGroupId.

**Comment by pkorolo** [comment]
gentlemen @arjenhuitema @jfaurskov let's sync during our weekly meeting; or I could sync with Jan tomorrow, to further clarify what is required (because to my point of view the naming itself is not unclear or subject to error, as long as it is consistent and suitably explained in the wiki docs).

**Comment by pkorolo** [comment]
@arjenhuitema please review the proposed changes in the deployment variable names, if they are now satisfactory and alleviate confusion with parameter(s). If still needed, I can also alter the  "parPolicyManagementGroupId" parameter name, as it appears (only) in the respective initiative assignment templates and the respective parameter files.
cc @jfaurskov

**Comment by pkorolo** [comment]
re-drafting to change the parameter name as well

**Comment by pkorolo** [comment]
@arjenhuitema I have finalized my PR with all requested changes; please review

cc @jfaurskov , just fyi

**Review by arjenhuitema — APPROVED** [review]
LGTM. Great work!

**Pull request merged**
